label: 'नियंत्रित सामग्री'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: फिल्टर
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      fields:
        title:
          label: शीर्षक
        type:
          label: 'सामग्री प्रकार'
        name:
          label: लेखक
        changed:
          label: अद्यतित
        operations:
          label: कार्यवाही
      filters:
        title:
          expose:
            label: शीर्षक
        type:
          expose:
            label: 'सामग्री प्रकार'
        langcode:
          expose:
            label: भाषा
      title: 'नियंत्रित सामग्री'
  moderated_content:
    display_title: 'नियंत्रित सामग्री'
